' Official Nykredit C4 colors and styles

' Colors
!global $NK_COMPONENT_BORDER_COLOR = "#A9783D"
!global $NK_COMPONENT_COLOR = "#BE8A4A"
!global $NK_CONTAINER_BORDER_COLOR = "#3C907B"
!global $NK_CONTAINER_COLOR = "#4F9E81"
!global $NK_ENTERPRISE_BORDER_COLOR = "#555555"
!global $NK_ENTERPRISE_COLOR = "#FFFFFF"
!global $NK_EXISTING_BORDER_COLOR = "#8A8A8A"
!global $NK_EXISTING_COLOR = "#969696"
!global $NK_FG_COLOR = "#FFFFFF"
!global $NK_SYSTEM_BORDER_COLOR = "#42688A"
!global $NK_SYSTEM_COLOR = "#4F7CA4"

UpdateElementStyle(component, $bgColor=$NK_COMPONENT_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_COMPONENT_BORDER_COLOR)
UpdateElementStyle(container, $bgColor=$NK_CONTAINER_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_CONTAINER_BORDER_COLOR)
UpdateElementStyle(external_person, $bgColor=$NK_EXISTING_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_EXISTING_BORDER_COLOR)
UpdateElementStyle(external_system, $bgColor=$NK_EXISTING_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_EXISTING_BORDER_COLOR)
UpdateElementStyle(person, $bgColor=$NK_SYSTEM_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_SYSTEM_BORDER_COLOR)
UpdateElementStyle(system, $bgColor=$NK_SYSTEM_COLOR, $fontColor=$NK_FG_COLOR, $borderColor=$NK_SYSTEM_BORDER_COLOR)

' Link styling
skinparam HyperlinkUnderline false
skinparam HyperlinkColor #444444

' Increase boundary thickness
skinparam rectangle<<boundary>> {
    BorderThickness 3
}

' Add a tag to a (possibly empty) list of tags
!function $nkAddTag($tag, $tags="")
    !$result = $tag
    !if ($tags != "")
        !$result = $tags + '+' + $tag
    !endif
    !return !$result
!endfunction

' Container_Boundary: solid thick container-colored border
skinparam rectangle<<nk_container_boundary>> {
    BorderStyle solid
    BorderThickness 5
}
AddElementTag("nk_container_boundary", $borderColor=$NK_CONTAINER_COLOR)
!unquoted procedure Container_Boundary($alias, $label, $tags="", $link="")
  !if ($tags != "")
    !$allTags = $tags + '+nk_container'
  !else
    !$allTags = 'nk_container'
  !endif
  ' $type defined via $tag style
  Boundary($alias, $label, "", $allTags, $link)
!endprocedure

' Enterprise_Boundary: solid thick black border
skinparam rectangle<<nk_enterprise_boundary>> {
    BorderStyle solid
}
AddElementTag("nk_enterprise_boundary", $borderColor="#000000")
!unquoted procedure Enterprise_Boundary($alias, $label, $tags="", $link="")
    Boundary($alias, $label, "Enterprise", $nkAddTag("nk_enterprise", $tags), $link)
!endprocedure

' System_Boundary: solid thick system-colored border
skinparam rectangle<<nk_system_boundary>> {
    BorderStyle solid
    BorderThickness 5
}
AddElementTag("nk_system_boundary", $borderColor=$NK_SYSTEM_COLOR)
!unquoted procedure System_Boundary($alias, $label, $tags="", $link="")
    Boundary($alias, $label, "System", $nkAddTag("nk_system", $tags), $link)
!endprocedure

' Define our custom legend
!procedure LAYOUT_WITH_LEGEND()
hide stereotype
legend right
|<color:$LEGEND_TITLE_COLOR>**Legend**</color> |
|<$NK_SYSTEM_COLOR> system / person |
|<$EXTERNAL_SYSTEM_BG_COLOR> existing system / person |
!if ($NK_DIAGRAM_TYPE == "container") || ($NK_DIAGRAM_TYPE == "component") || ($NK_DIAGRAM_TYPE == "dynamic") || ($NK_DIAGRAM_TYPE == "deployment")
|<$NK_CONTAINER_COLOR> container |
!endif
!if ($NK_DIAGRAM_TYPE == "component")
|<$NK_COMPONENT_COLOR> component |
!endif
endlegend
!endprocedure

' Define our custom relationship function with line break patch
!function $getRel($direction, $alias1, $alias2, $label, $techn, $descr, $sprite, $tags, $link)
  !$sprite = $toRelArg($sprite, $tags, "RelTagSprite")
  !$techn = $toRelArg($techn, $tags, "RelTagTechn")
  !$rel = $alias1 + ' ' + $direction + ' ' + $alias2
  !if ($tags != "")
    !$rel = $rel + ' ' + $toStereos($tags)
  !endif
  !$rel = $rel + ' : '
  !if ($sprite != "")
    !$rel = $rel + $getSprite($sprite) + ' '
  !endif
  !if ($link != "")
    !$rel = $rel + '**[[' + $link + ' ' + $label + ']]**'
  !else
    !$rel = $rel + '**' + $label + '**'
  !endif
  !if ($techn != "")
    ' line break is not deterministic, calculate it
    !$rel = $rel + '\n//<size:' + $TECHN_FONT_SIZE + '>[' + $breakTechn($techn, $REL_TECHN_MAX_CHAR_WIDTH) + ']</size>//'
  !endif
  !if ($descr != "")
    ' line break is not deterministic, calculate it
    ' Nykredit: Use only a single line break
    !$rel = $rel + '\n' + $breakDescr($descr, $REL_DESCR_MAX_CHAR_WIDTH)
  !endif
  !$prop = $getProps()
  !if ($prop != "")
    ' reuse table
    !$rel = $rel + $prop
  !endif
  !return $rel
!endfunction
